### ISSUE TITLE
entrypoint requires the handler name to be the first argument

### ISSUE THREAD

**Issue by tho-asterist** [aws-samples/php-examples-for-aws-lambda#23]
Hi everyone,

I'm trying to build the local environment for develop Lambda functions with PHP.

I modify the `Dockerfile` (https://github.com/aws-samples/php-examples-for-aws-lambda/blob/master/0.7-PHP-Lambda-functions-with-Docker-container-images/Dockerfile)

`CMD ["index", "_HANDLER=/tasks/get_data"]`

Then got the error

`entrypoint requires the handler name to be the first argument`

_**What should the handler name be?**_

Example I have the `/tasks` folder that contains the functions `get_data`, `post_data`.
For `serverless.yml`, it will be config like this

```
functions:
  task_get_data:
    timeout: 60
    handler: tasks/get_data.php
    layers:
      -  ${bref:layer.php-73}
  task_post_data:
    timeout: 60
    handler: tasks/post_data.php
    layers:
      -  ${bref:layer.php-73}
```

How can I test these functions in local with docker container images?

I'm looking forward to your help. 
Thank you so much.
